services:
  nginx-golang:
    image: nginx:1.21.1
    container_name: nginx-golang
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - ./docker/nginx/logs/:/var/log/nginx
